default: &default
  adapter: postgresql
  pool: 5 # Specifies the maximum number of connections that can be opened
  timeout: 5000 # in milliseconds. This is how long the app will wait for a database response
  encoding: unicode

development:
  <<: *default # inherits from default
  database: tasker_development
  port: 5432
  user:
  password:
test:
  <<: *default
  database: tasker_test

production:
  <<: *default
  database: tasker
